server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://google/orderdb?cloudSqlInstance=${CLOUDSQL_INSTANCE}&socketFactory=${DB_SOCKET_FACTORY}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,env