server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=${CLOUDSQL_INSTANCE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,env