server:
  port: 8080

spring:
  application:
    name: z-order-service
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console