name: CI-CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build com Maven
        run: mvn clean package -Denable.preview=true --batch-mode --errors --fail-at-end

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build e Push Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest

      - name: Setup gCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy order-service \
            --image=${{ secrets.DOCKER_USERNAME }}/order-service:latest \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated \
            --set-env-vars SPRING_PROFILES_ACTIVE=dev