name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build com Maven
        run: mvn clean package -Denable.preview=true --batch-mode --errors --fail-at-end

      - name: Testes
        run: mvn test -Denable.preview=true

      - name: Check JAR
        run: ls -lh target/*.jar

      - name: Build imagem Docker
        run: docker build -t zanelato/order-service .

      - name: Testar container Docker
        run: docker run -d -p 8080:8080 --name test-order zanelato/order-service

      - name: Esperar e testar POST /orders
        run: |
          sleep 10
          curl --fail -X POST http://localhost:8080/orders \
            -H "Content-Type: application/json" \
            -d '{"product":"Notebook","quantity":2}'
